import matplotlib.pyplot as plt 
import numpy as np
x=np.linspace(-5,5,100)
y=np.linspace(-5,5,100)
x,y=np.meshgrid(x,y)
z=np.sin(np.sqrt(x**2+y**2))

fig=plt.figure()
ax=fig.add_subplot(121,projection='3d')
ax.plot_wireframe(x,y,z)
ax.set_title("wireframe")
ax.set_xlabel("X-axis")
ax.set_ylabel("Y-axis")
ax.set_zlabel("Z-axis")
ax=fig.add_subplot(122,projection='3d')
ax.plot_surface(x,y,z,cmap='viridis')
ax.set_title("surface")
ax.set_xlabel("X-axis")
ax.set_ylabel("Y-axis")
ax.set_zlabel("Z-axis")
plt.show()